### ISSUE TITLE
Why is Google Maps incluced?

### ISSUE THREAD

**Issue by rugk** [lineageos4microg/android_prebuilts_prebuiltapks#1]
I hope that this is not the – as the Readme states – "official" version, because then it would be proprietary and from Google. That would be exactly the opposite of what this project aims at.

So what is it? And why is it included (and preinstalled?)?

**Comment by corna** [comment]
Don't worry, it's just [microG's mapsv1](https://github.com/microg/android_frameworks_mapsv1) which, like many microG components, have the same signature of the Google apps. You can verify it by downloading the [microG release ZIP](https://github.com/microg/android_frameworks_mapsv1/releases): the jar included in this repo is the same as the jar in the mapsv1.flashable.zip/system/framework/.

You can also double-check it by running an app which requires the (now legacy) mapsv1 and checking that the loaded maps are from OpenStreetMaps, and not from Google Maps.

(I should add a note on that package)

**Comment by rugk** [comment]
Interesting project. Maybe you can expand the Readme in https://github.com/microg/android_frameworks_mapsv1, because I still have some questions:
1. Can it be deactivated?
2. Why is not it included in the "official" microg package?
3. Does it always connect to the "official" Google Maps or can I maybe use it (similar to UnifiedNLP) as a dropin replacement with OpenStreetMaps etc.?

**Edit:** Okay, your attribution statement clarifies 4. a bit, but triggers new questions:
1. Does it need OsmAnd to be installed?
2. If OsmAnd is installed, does it use all offline data etc. from OsmAnd?
3. If 1. is false, can we maybe have a smaller package, which only works with OsmAnd, so if I want to install the app anyway, I do not need to waste space/duplicate code?
4. Could I also use other map providers like (online versions of) Mapbox?

**Comment by corna** [comment]
First set of questions:
1. Yes, but you have to create a recovery ZIP which:
   * removes it
   * install an update script, which removes it automatically at each upgrade
2. Because the mapsv1 have been deprecated by google and it requires a ZIP to install it. Its replacement, mapsv2, is already included in GmsCore
3. There is no plugin interface, it always uses OpenStreetMaps (not Google Maps)

Second set:
1. No
2. I honestly don't know, I think is always uses online services
3. No, it's a legacy package (mainly to prevent app crashes), and I don't think it will be updated much in the future
4. No, see 3

**Comment by rugk** [comment]
Ah okay, so it is only for compatibility. Okay…
