### ISSUE TITLE
F-Droid app and it's extension needs to be updated

### ISSUE THREAD

**Issue by AntiWeebPenguin** [lineageos4microg/android_prebuilts_prebuiltapks#45]
F-Droid app and the privileged extension needs to be updated. I'm not very skilled for this, but i can try to help if you want.

**Comment by bananer** [comment]
Why do you think so? Version 1.11 (1011050), which is included in this repo is the latest stable release. https://f-droid.org/packages/org.fdroid.fdroid/

**Comment by AntiWeebPenguin** [comment]
Oh, was it recently updated? because when i build the ROM and open the app for the first time it tells me to update. The F-Droid version that comes pre-installed for me is 1.10.

**Comment by bananer** [comment]
Check the [commits](https://github.com/lineageos4microg/android_prebuilts_prebuiltapks/commits/master). It was uploaded on Jan 7, literally the day of the F-Droid release.

**Comment by AntiWeebPenguin** [comment]
The latest F-Droid version is 1.11

**Comment by bananer** [comment]
You're absolutely right, i misread the numbers.

I'm not sure if providing a pull request would help here, since the maintainers of this repo would still have to verify the binary.

If you're building your own rom, you can of course fork this repo, update the apks there and point the manifest for your build to the fork.
